sudo: false
language: node_js
node_js:
  - '0.12'
  - '1'
  - '2'
  - '3'
  - '4'
script:
  - "npm run test-cov"
after_script:
  - "npm i codecov.io && cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js"
