jobs:
- template: azure-pipelines.template.yml
  parameters:
    name: win_node_4
    vmImage: 'vs2017-win2016'
    node_version: 4
    install_script: 'npm i -g npminstall && npminstall'
    test_script: 'npm run ci'

- template: azure-pipelines.template.yml
  parameters:
    name: win_node_6
    vmImage: 'vs2017-win2016'
    node_version: 6
    install_script: 'npm i -g npminstall && npminstall'
    test_script: 'npm run ci'

- template: azure-pipelines.template.yml
  parameters:
    name: win_node_8
    vmImage: 'vs2017-win2016'
    node_version: 8
    install_script: 'npm i -g npminstall && npminstall'
    test_script: 'npm run ci'

- template: azure-pipelines.template.yml
  parameters:
    name: win_node_10
    vmImage: 'vs2017-win2016'
    node_version: 10
    install_script: 'npm i -g npminstall && npminstall'
    test_script: 'npm run ci'

- template: azure-pipelines.template.yml
  parameters:
    name: macos_node_4
    vmImage: 'xcode9-macos10.13'
    node_version: 4
    install_script: 'npm i -g npminstall && npminstall'
    test_script: 'npm run ci'

- template: azure-pipelines.template.yml
  parameters:
    name: macos_node_6
    vmImage: 'xcode9-macos10.13'
    node_version: 6
    install_script: 'npm i -g npminstall && npminstall'
    test_script: 'npm run ci'

- template: azure-pipelines.template.yml
  parameters:
    name: macos_node_8
    vmImage: 'xcode9-macos10.13'
    node_version: 8
    install_script: 'npm i -g npminstall && npminstall'
    test_script: 'npm run ci'

- template: azure-pipelines.template.yml
  parameters:
    name: macos_node_10
    vmImage: 'xcode9-macos10.13'
    node_version: 10
    install_script: 'npm i -g npminstall && npminstall'
    test_script: 'npm run ci'

